services:
  app:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: lit_autoencoder_app # Explicit way to define the image name

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"
    
    # Mount the current directory to the app directory in the container
    volumes:
      - .:/app
    
    environment:
      - PYTHONPATH=/app/src

    # Use environment variables from an external file
    # env_file:
    #   - .env

    # Default command to start the FastAPI application
    command: ["uvicorn", "demo:app", "--host", "0.0.0.0", "--port", "8000"]
