# Description: Docker Compose configuration file for the FastAPI application.

# The x-args section defines a reusable set of arguments using YAML anchors.
# - Used to pass build arguments ("UV_VER") to the Dockerfile.
x-args: &default-args
  WORKSPACE_NAME: "app"
  UV_VER: "python3.12-bookworm"

services:
  app:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *default-args # The <<: *default-args syntax merges the default-args into the args section of the build configuration.
    image: lit_autoencoder_app # Explicit way to define the image name

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"
    
    # Default command to start the FastAPI application.
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  app-optimized-docker:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: multistage.Dockerfile
      args:
        <<: *default-args # The <<: *default-args syntax merges the default-args into the args section of the build configuration.
    image: lit_autoencoder_app # Explicit way to define the image name

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    # Default command to start the FastAPI application.
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
