site_name: UV Data Science Project Template
nav:
  - Home: index.md
  - Guides:
    - Ruff: guides/ruff.md
    - UV: guides/uv.md
    - PyTest: guides/pytest.md
    - PyRight: guides/pyright.md
    - Pre-Commit: guides/pre-commit.md
    - MkDocs: guides/mkdocs.md
    - Docker-Production: guides/docker_prod.md
    - Docker-VSCode-DevContainer: guides/docker_vscode_devcontainer.md
    - CI-GitHub: guides/ci_github.md
  - Source Code API Reference:
      - Autoencoder: api/autoencoder.md
      - Training: api/training.md
      - FastAPI: api/fastapi_app.md
theme:
  name: material
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  