site_name: UV Data Science Project Template
nav:
  - Home: index.md
  - Guides:
    - UV: guides/uv.md
    - Ruff: guides/ruff.md
    - PyRight: guides/pyright.md
    - PyTest: guides/pytest.md
    - Pre-Commit: guides/pre_commit.md
    - CI-GitHub: guides/ci_github.md
    - MkDocs: guides/mkdocs.md
    - Docker-Production: guides/docker_prod.md
    - Docker-VSCode-DevContainer: guides/docker_vscode_devcontainer.md
  - Project Configuration:
    - pyproject.toml: pyproject.md
  - Source Code API Reference:
      - Main: api/main.md
      - Autoencoder: api/autoencoder.md
      - Training: api/training.md
      - FastAPI: api/fastapi_app.md
  - Notebooks:
    - Main: notebooks/app_without_fastapi.ipynb
theme:
  name: material
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - mkdocs-jupyter:
    - ignore_h1_titles: True # Ignore using first h1 as title, instead use filename.
  