site_name: UV Data Science Project Template
repo_url: https://github.com/tiefenthaler/uv-datascience-project-template
nav:
  - Home: index.md
  - Guides:
    - guides/index.md
    - UV: guides/uv.md
    - Ruff: guides/ruff.md
    - PyRight: guides/pyright.md
    - PyTest: guides/pytest.md
    - Pre-Commit: guides/pre_commit.md
    - CI-GitHub: guides/ci_github.md
    - MkDocs: guides/mkdocs.md
    - Docker-Production: guides/docker_prod.md
    - Docker-VSCode-DevContainer: guides/docker_vscode_devcontainer.md
  - Source Code API Reference:
      - api/index.md
      - Autoencoder: api/autoencoder.md
      - Training: api/training.md
      - FastAPI: api/fastapi_app.md
  # NOTE: Does not support nested lists.
  - Notebooks: 
    - Jupyter Notebook - App: notebooks/app_without_fastapi.ipynb
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections # TODO: Check, if this is needed.
    - navigation.expand
    - navigation.path
    - navigation.top
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
  - mkdocs-jupyter:
      # ignore_h1_titles: true # Ignore using first h1 as title, instead use filename.
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences