[project]
name = "dev-container-uv-datascience"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0, <3.13.0"
dependencies = [
    "fastapi>=0.115.6",
    "lightning>=2.4.0",
    "pydantic>=2.10.4",
    "toml-sort>=0.24.2",
    "torch>=2.4.1",
    "torchvision>=0.20.1",
    "uvicorn>=0.34.0"
]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.1",
    "pytest>=8.1.1",
    "uv>=0.5.5"
]
lint = [
    "ruff>=0.8.1",
    "toml-sort>=0.24.2"
]
[tool.pylint]

[tool.pylint.'FORMAT']
max-line-length = 99

# NOTE: to sort, run: "uv run toml-sort pyproject.toml"
[tool.tomlsort]
in_place = true
no_sort_tables = true
sort_inline_arrays = true
spaces_before_inline_comment = 4
spaces_indent_inline_array = 4

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
