version: "3.8" # Specifies which version of the Docker Compose file format to use

x-args: &default-args
  WORKSPACE_NAME: &workspace_name "workspace"
  UV_VER: "python3.12-bookworm"

services: # Top level element to configure the arguments of multiple services
  myproject: # "project" refers to the name of your project/application for which configurations are defined. Multiple projects can be configured.
    build: # Tells Docker Compose to build the Docker image using the Dockerfile in the specified directory.
      context: .
      dockerfile: ./Dockerfile.debug
      args:
        <<: *default-args # The <<: *default-args syntax merges the default-args into the args section of the build configuration.
    image: dat/dev-container-uv-datascience # Explicit way to define the image name
    # networks:
    #   - app-net

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    # Volumes are persistent data stores (outside container), mounted to be usable by the container
    volumes:
      - ../:/*workspace_name

    working_dir: /*workspace_name

    # Environment variables to be set in the container, point to local files (⚡ local venv path ⚡).
    # environment:
      # - PYTHONPATH=/*workspace_name/src

    # Use environment variables from an external file
    # env_file:
    #   - .env

    # Default command to start the dev container
    command:
      - sh -c "chmod -R 777 /workspace && tail -f /dev/null" # Set permissions on the working directory for root user