# .github/workflows/check_all_workflows.yml

name: CI Workflows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Status
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed',
              branch: 'main'
            });

            const allSuccess = response.data.workflow_runs.every(
              run => run.status === 'completed' && run.conclusion === 'success'
            );

            return allSuccess;

      - name: Set Output
        if: always()
        run: echo "workflow_success=${{ steps.check.outputs.result }}" >> $GITHUB_OUTPUT
