name: Publish Docs via GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
        
# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v1

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
